# Suggesting the Expense Type for Department for Transport spend lines

**Patrick Gilliland**

**Question.** Can a model trained on the Department for Transport's past ledger lines suggest the right Expense Type for a new line over £25,000, and what share of lines could it code confidently enough to leave the rest to a person?

**Task 1: the problem and the dataset.** Every payment line a finance team posts carries an account code, which in this data is the `Expense Type`. The problem is to suggest that code for a new line from the other fields on the line, such as the supplier and the item text. In accounting terms this is general ledger account classification: assigning an account code to each posting line. The task is supervised learning (classification), and it is multi-class, because `Expense Type` holds many labels. The dataset is [Spend over £25,000 in the Department for Transport and its arms-length bodies](https://www.data.gov.uk/dataset/804be0c6-ae01-4899-bbb9-2317dff1a4f9/financial-transactions-data-dft), which the Department for Transport (DfT) publishes on data.gov.uk as one CSV file a month. I use the 48 months from April 2022 to March 2026. `build_dataset.py` stacks the original monthly files in `dft_originals/` into `dft_spend_over_25k_2022-04_to_2026-03.csv`, beside this notebook, without changing any cell. Contains public sector information licensed under the Open Government Licence v3.0.

**Report.** The Machine Learning Analysis Report is one PDF under the two names the brief uses: `module_summary.pdf`, and an identical copy named `Machine_Learning_Analysis_Report.pdf`.

## Data preparation

### Setup

In [1]:
import hashlib
import os
import platform
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd
import sklearn

# I show every column and whole cell text, up to 500 rows so the anomaly
# listings appear in full, and figures with two decimal places and thousands
# separators, so the wide tables below read without scientific notation.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 500)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", "{:,.2f}".format)

# Every step below that draws at random takes this seed, so a rerun gives the
# same numbers.
SEED = 42

print(f"Python {platform.python_version()}")
print(f"NumPy {np.__version__}")
print(f"pandas {pd.__version__}")
print(f"scikit-learn {sklearn.__version__}")
print(f"Matplotlib {matplotlib.__version__}")
print(f"Random seed: {SEED}")
print(f"CPU cores: {os.cpu_count()}")

Python 3.12.3
NumPy 2.5.3
pandas 3.0.6
scikit-learn 1.9.1
Matplotlib 3.11.2
Random seed: 42
CPU cores: 24

**Hardware.** I run everything on the CPU, with no GPU. The models are scikit-learn's, and the whole file fits in memory, so I load it in one go. Where a scikit-learn step can use every core, it gets `n_jobs=-1`.

### Task 2: Load and inspect the dataset

In [2]:
DATA = Path("dft_spend_over_25k_2022-04_to_2026-03.csv")
EXPECTED_SHA256 = (
    "3d9d7f911ef00f9394c07077ebb1ec161efbeb7f3073824c801a662aac212bd4"
)

if not DATA.exists():
    raise FileNotFoundError(
        f"{DATA} is not beside this notebook. Build it from the 48 original "
        "monthly files in dft_originals/ with: python build_dataset.py"
    )
digest = hashlib.sha256(DATA.read_bytes()).hexdigest()
print(f"File: {DATA}, {DATA.stat().st_size:,} bytes")
print(f"SHA-256: {digest}")
# Every figure below comes from this exact file, so I stop rather than
# analyse a different one.
if digest != EXPECTED_SHA256:
    raise ValueError(
        f"{DATA} is not the file build_dataset.py writes from the 48 original "
        "files. Rebuild it with: python build_dataset.py"
    )
print(
    "It matches the file build_dataset.py writes from the 48 original files."
)

# I read every cell as the text DfT published. The amounts carry a pound sign
# and commas, and by default pandas would turn text such as "#N/A" into a
# blank, so nothing is converted on load.
df = pd.read_csv(DATA, dtype=str, keep_default_na=False)
print(f"Loaded: {len(df):,} rows, {df.shape[1]} columns")

File: dft_spend_over_25k_2022-04_to_2026-03.csv, 25,396,696 bytes
SHA-256: 3d9d7f911ef00f9394c07077ebb1ec161efbeb7f3073824c801a662aac212bd4
It matches the file build_dataset.py writes from the 48 original files.
Loaded: 126,346 rows, 11 columns

In [3]:
df.head()

,Department Family,Entity,Date,Expense Type,Expense Area,Supplier,Transaction No,Item Text,£,Postal Code,source_file
0,Department for Transport,Department for Transport,05/04/2022,Grt Aid to NDPBs,DG Rail Strategy and Services Group,NETWORK RAIL ISTRE (CAPITAL GRANTS),2000000612,NR GRANT APRIL 2 SR 9000946295,"£418,408,000.00",NW1 2DN,dft_2022-04.csv
1,Department for Transport,Department for Transport,29/04/2022,Grt Aid to NDPBs,"DG Roads, Places and Environment",National Highways Limited,2000003150,Grant in Aid NH for May 2022,"£298,000,000.00",B1 1RN,dft_2022-04.csv
2,Department for Transport,Department for Transport,29/04/2022,CurrGrtOth to NDPBs,DG Rail Strategy and Services Group,NETWORK RAIL ISTRE (CAPITAL GRANTS),2000003127,NR Grant - DUE 03/05/2022 - SR 9000953144,"£151,086,319.00",NW1 2DN,dft_2022-04.csv
3,Department for Transport,High Speed Two (HS2) Limited,07/04/2022,AUC - Phase 1,000000 AUC - Phase 1,BALFOUR BEATTY VINCI JV - HS2 (N2),#,MWCC Stage One TP,"£135,660,641.62",#,dft_2022-04.csv
4,Department for Transport,Department for Transport,05/04/2022,Cap Grt NDPBs & CG,DG Rail Strategy and Services Group,NETWORK RAIL ISTRE (CAPITAL GRANTS),2000000612,NR GRANT APRIL 2 SR 9000946295,"£117,640,000.00",NW1 2DN,dft_2022-04.csv

In [4]:
published = [name for name in df.columns if name != "source_file"]
stripped = df.apply(lambda column: column.str.strip())
blank_row = stripped[published].eq("").all(axis=1)
blank_files = ", ".join(df.loc[blank_row, "source_file"].unique())
print(
    f"Rows: {len(df):,}, of which {blank_row.sum():,} have every published "
    f"cell blank, all from {blank_files}"
)

# The publisher marks a missing value with "#", and a few cells hold the
# spreadsheet error "#N/A", so I count those beside the truly blank cells.
column_check = pd.DataFrame(
    {
        "dtype": df.dtypes.astype(str),
        "blank": stripped.eq("").sum(),
        '"#"': stripped.eq("#").sum(),
        '"#N/A" or "N/A"': stripped.isin(["#N/A", "N/A"]).sum(),
        "spaces at either end": df.ne(stripped).sum(),
        "distinct values": df.where(stripped.ne("")).nunique(),
    }
)
column_check

Rows: 126,346, of which 657 have every published cell blank, all from dft_2022-05.csv

                  dtype  blank    "#"  "#N/A" or "N/A"  spaces at either end  distinct values
Department Family   str    657      0                0                   137                3
Entity              str    657      0                0                  1260               15
Date                str    657      0                0                     1             1387
Expense Type        str    657      0                0                   666             1054
Expense Area        str    657      0                4                   756              976
Supplier            str    657      0                0                   381             4015
Transaction No      str    657  10192                2                     0            97175
Item Text           str    657  16139               57                  1977            20231
£                   str    657      0                0                 50587           104351
Postal Code         str    657  16978                0                   210             2791
source_file         str      0      0                0                     0               48

In [5]:
def parse_fields(frame, amount="£", date="Date", source="source_file"):
    """Return a copy of frame with the amount, date and month as typed columns.

    Three columns are added. amount is the amount in pounds as a float,
    read from text such as " £1,234.50 ". date is the payment date, read as
    day/month/year, or as day.month.year where the file uses dots. month is
    the month of the file the row came from, "YYYY-MM", taken from the
    source file's name. A value that cannot be read is left blank (NaN or
    NaT). frame is not changed.

    Parameters
    ----------
    frame : pandas.DataFrame
        The rows as published, every column text.
    amount, date, source : str
        The names of the amount, date and source file columns.

    Returns
    -------
    pandas.DataFrame
        frame's columns unchanged, then amount, date and month.
    """
    out = frame.copy()
    money = frame[amount].str.strip().str.replace("£", "", regex=False)
    money = money.str.replace(",", "", regex=False)
    out["amount"] = pd.to_numeric(money, errors="coerce").astype(float)
    text = frame[date].str.strip()
    slashes = pd.to_datetime(text, format="%d/%m/%Y", errors="coerce")
    dots = pd.to_datetime(text, format="%d.%m.%Y", errors="coerce")
    out["date"] = slashes.fillna(dots)
    out["month"] = frame[source].str.extract(r"(\d{4}-\d{2})", expand=False)
    return out

In [6]:
df = parse_fields(df)
content = ~blank_row
written = df.loc[content, "Date"]
slash_form = written.str.fullmatch(r"\d{2}/\d{2}/\d{4}")
dot_form = written.str.fullmatch(r"\d{2}\.\d{2}\.\d{4}")
spaced = written.ne(written.str.strip())
print(
    f"Amounts read: {df.loc[content, 'amount'].notna().sum():,} of "
    f"{content.sum():,} lines with content"
)
print(
    f"Dates read: {df.loc[content, 'date'].notna().sum():,} of "
    f"{content.sum():,}; {slash_form.sum():,} written dd/mm/yyyy, "
    f"{dot_form.sum():,} written dd.mm.yyyy, {spaced.sum():,} with spaces "
    "round it"
)
months = df["month"]
print(f"Months: {months.nunique()}, {months.min()} to {months.max()}")
print(f"Published total: £{df['amount'].sum():,.2f}")
print(
    f"Smallest line: £{df['amount'].min():,.2f}; "
    f"largest: £{df['amount'].max():,.2f}"
)
df[["amount", "date", "month"]].dtypes

Amounts read: 125,689 of 125,689 lines with content
Dates read: 125,689 of 125,689; 125,660 written dd/mm/yyyy, 28 written dd.mm.yyyy, 1 with spaces round it
Months: 48, 2022-04 to 2026-03
Published total: £177,111,208,418.51
Smallest line: £25,000.00; largest: £786,575,788.00

amount           float64
date      datetime64[us]
month                str
dtype: object

**What loaded.** The file loads as 126,346 rows and 11 columns: the ten columns DfT publishes and `source_file`, which names the monthly file each row came from. I read every cell as text, so every column loads as text. `parse_fields` then adds the amount as a number, the date as a date and the file's month. Every one of the 125,689 lines with content has an amount and a date I can read, across 48 months.

**Obvious data quality issues.**

- 657 rows are blank in every published column, all from the May 2022 file. The build keeps them, so the combined file holds every row DfT published.
- The amount is text with a pound sign and commas, and 50,587 amount cells have spaces round them. Every amount reads, from £25,000.00 to £786,575,788.00, so no line is a credit.
- The date is text too. 125,660 lines write it dd/mm/yyyy, 28 use dots and 1 has spaces round it. `parse_fields` reads all three forms.
- The publisher writes "#" for a missing value: in 10,192 transaction numbers, 16,139 item texts and 16,978 postcodes. The spreadsheet error "#N/A" or "N/A" sits in 4 Expense Area cells, 2 transaction numbers and 57 item texts. I read the file with `keep_default_na=False`, so pandas cannot turn any of these into a blank without my knowing.
- Names are not always written one way. Department Family has 3 spellings for one department, Entity has 15 values, with spaces round 1,260 of its cells, and Expense Type has 1,054 labels, some of which differ only in case, spacing or punctuation.

I list each of these, and the other anomalies I found, with its count and value in the anomaly list below, before anything is cleaned.

### The anomaly list

Before anything is cleaned, I list every anomaly I could find in the 48 months, kind by kind. For each kind the anomaly list gives the lines it touches, their value, and the published total with and without them. Each kind also has my proposed treatment, flag, keep or exclude, which waits for a ruling. Nothing is removed here: Task 3 applies the rulings, keeps every raw row and gives any excluded line its reason. First come the listings the list draws on: the original files, the time-ordered split, the label variants, the truncation pairs and National Highways' newer "TA Cost AUC" labels.

In [7]:
def file_anomalies(manifest, schema, usual_encoding="cp1252"):
    """Return the original files whose encoding or header is not the usual one.

    A file is listed when its encoding is not usual_encoding, or when a
    column in its header is named differently from schema at the same
    position. manifest is not changed.

    Parameters
    ----------
    manifest : pandas.DataFrame
        One row per original file: file, month, encoding, rows (text, as
        the manifest stores it) and header, a tuple of its trimmed column
        names.
    schema : list of str
        The column names the build maps every header to.
    usual_encoding : str, default "cp1252"
        The encoding most of the files use.

    Returns
    -------
    pandas.DataFrame
        Indexed by file: month, encoding, rows as a number, and the columns
        named differently, each as '"published name" for "schema name"',
        or "" when the header is the usual one.
    """
    renamed = manifest["header"].map(
        lambda header: "; ".join(
            f'"{name}" for "{wanted}"'
            for name, wanted in zip(header, schema)
            if name != wanted
        )
    )
    out = manifest[["file", "month", "encoding"]].assign(
        rows=manifest["rows"].astype(int),
        **{"columns named differently": renamed},
    )
    odd = (out["encoding"] != usual_encoding) | (renamed != "")
    return out[odd].set_index("file")

In [8]:
# The build reads each original with the encoding its manifest gives, and
# maps each header to one set of column names. I read both off the
# originals here, so the files that needed either are shown, not assumed.
ORIGINALS = Path("dft_originals")
manifest = pd.read_csv(ORIGINALS / "MANIFEST.csv", dtype=str)
manifest["header"] = [
    tuple(
        name.strip()
        for name in pd.read_csv(
            ORIGINALS / row.file, encoding=row.encoding, nrows=0
        ).columns
    )
    for row in manifest.itertuples()
]
file_check = file_anomalies(manifest, schema=published)
cp850_files = list(file_check.index[file_check["encoding"] == "cp850"])
renamed = file_check["columns named differently"] != ""
drift_files = list(file_check.index[renamed])
print(
    f"Original files: {len(manifest)}; not cp1252: "
    f"{(file_check['encoding'] != 'cp1252').sum()}; with a column named "
    f"differently: {len(drift_files)}"
)
file_check

Original files: 48; not cp1252: 5; with a column named differently: 5

                   month   encoding  rows                      columns named differently
file
dft_2022-05.csv  2022-05     cp1252  3271          "Expense Area rev" for "Expense Area"
dft_2022-08.csv  2022-08     cp1252  2232          "Expense Area rev" for "Expense Area"
dft_2023-04.csv  2023-04      cp850  2879  "Departmental Family" for "Department Family"
dft_2023-07.csv  2023-07      cp850  2842
dft_2023-08.csv  2023-08      cp850  2596
dft_2024-03.csv  2024-03     cp1252  3515      "Transaction Number" for "Transaction No"
dft_2025-01.csv  2025-01  utf-8-sig  2556
dft_2025-02.csv  2025-02  utf-8-sig  2586
dft_2025-07.csv  2025-07     cp1252  2586  "Departmental Family" for "Department Family"

**The original files.** Of the 48 original files, 5 are not cp1252. January and February 2025 are UTF-8 and start with a byte-order mark. April, July and August 2023 store the pound sign as the single byte 0x9C, which cp850 reads as "£", so the build reads those 3 files as cp850. Separately, 5 files name a column differently, such as "Expense Area rev" in May and August 2022, and the build maps each one to the usual name. Neither changes a published value, so I propose to keep the lines from these files as they are.

In [9]:
def assign_split(
    frame, month="month", training_end="2025-06", validation_end="2025-09"
):
    """Return the time-ordered split each row falls in, from its month.

    A row is in training up to and including training_end, in validation
    up to and including validation_end, and in test after that. Months are
    "YYYY-MM" text, which sorts in time order. frame is not changed.

    Parameters
    ----------
    frame : pandas.DataFrame
        Rows with a month column.
    month : str, default "month"
        The month column.
    training_end, validation_end : str
        The last month of training and of validation.

    Returns
    -------
    pandas.Series
        "training", "validation" or "test" on frame's index, named split.
    """
    months = frame[month]
    split = np.where(
        months <= training_end,
        "training",
        np.where(months <= validation_end, "validation", "test"),
    )
    return pd.Series(split, index=frame.index, name="split")

In [10]:
df["split"] = assign_split(df)
lines = df[content]
for name in ("training", "validation", "test"):
    in_split = lines.loc[lines["split"] == name, "month"]
    print(
        f"{name}: {in_split.min()} to {in_split.max()}, "
        f"{in_split.nunique()} months, {len(in_split):,} lines"
    )

training: 2022-04 to 2025-06, 39 months, 102,081 lines
validation: 2025-07 to 2025-09, 3 months, 7,291 lines
test: 2025-10 to 2026-03, 6 months, 16,317 lines

In [11]:
def label_variants(frame, column="Expense Type"):
    """Return every label that is another spelling of a commoner label.

    Two labels are spellings of one label when they match once case and
    every character that is not a letter or a digit are ignored. In each
    group the spelling with the most lines is the commonest, and a tie goes
    to the spelling that sorts first. Every other spelling is listed with
    the kind of difference, the first of these that applies:

    - spaces: it matches once runs of spaces are closed up and the ends
      trimmed;
    - case: it then matches ignoring case;
    - dash: it then matches once each en dash, em dash or "?" is read as a
      hyphen;
    - separator: any other difference, such as "/" for "-".

    Blank labels are left out. frame is not changed.

    Parameters
    ----------
    frame : pandas.DataFrame
        One row per line.
    column : str, default "Expense Type"
        The label column.

    Returns
    -------
    pandas.DataFrame
        One row per spelling that is not the commonest: label, commonest
        spelling, kind, lines and lines in commonest. Sorted by kind in the
        order above, then by lines, most first.
    """
    labels = frame[column]
    counts = labels[labels.str.strip() != ""].value_counts()
    table = pd.DataFrame({"label": counts.index, "lines": counts.to_numpy()})
    table = table.sort_values(["lines", "label"], ascending=[False, True])
    table["key"] = table["label"].str.casefold()
    table["key"] = table["key"].str.replace(r"[^a-z0-9]", "", regex=True)
    group = table.groupby("key")
    table["commonest spelling"] = group["label"].transform("first")
    table["lines in commonest"] = group["lines"].transform("first")
    out = table[table["label"] != table["commonest spelling"]].copy()

    label = out["label"]
    best = out["commonest spelling"]
    as_hyphen = str.maketrans({chr(0x2013): "-", chr(0x2014): "-", "?": "-"})
    closed = label.str.replace(r"\s+", " ", regex=True).str.strip()
    closed_best = best.str.replace(r"\s+", " ", regex=True).str.strip()
    hyphened = closed.str.translate(as_hyphen).str.casefold()
    hyphened_best = closed_best.str.translate(as_hyphen).str.casefold()
    kinds = ["spaces", "case", "dash"]
    out["kind"] = np.select(
        [
            closed == closed_best,
            closed.str.casefold() == closed_best.str.casefold(),
            hyphened == hyphened_best,
        ],
        kinds,
        default="separator",
    )
    out["order"] = out["kind"].map({kind: i for i, kind in enumerate(kinds)})
    out["order"] = out["order"].fillna(len(kinds))
    out = out.sort_values(
        ["order", "lines", "label"], ascending=[True, False, True]
    )
    columns = ["label", "commonest spelling", "kind", "lines"]
    return out[columns + ["lines in commonest"]].reset_index(drop=True)

In [12]:
variants = label_variants(df)
# I rank each spelling by its lines in the training months, ties in label
# order, so a pair with both spellings among the commonest types shows up.
in_training = lines.loc[lines["split"] == "training", "Expense Type"]
ranked = in_training.value_counts().sort_index()
ranked = ranked.sort_values(ascending=False, kind="stable")
rank = pd.Series(range(1, len(ranked) + 1), index=ranked.index)
variants["training rank"] = variants["label"].map(rank).astype("Int64")
variants["training rank (commonest)"] = (
    variants["commonest spelling"].map(rank).astype("Int64")
)
both_top = (variants["training rank"] <= 50) & (
    variants["training rank (commonest)"] <= 50
)
print(
    f"Groups: {variants['commonest spelling'].nunique()}; spellings that "
    f"are not the commonest: {len(variants)}, on "
    f"{variants['lines'].sum():,} lines"
)
for kind, group in variants.groupby("kind", sort=False):
    print(f"  {kind}: {len(group)} spellings, {group['lines'].sum():,} lines")
print(
    "Spellings where both it and its commonest spelling are among the 50 "
    f"commonest types in training: {both_top.sum()}"
)
for row in variants[both_top].itertuples():
    print(f'  "{row.label}" for "{row._2}"')

# I put each label in quotes, so a space at either end shows.
labels = ["label", "commonest spelling"]
shown = variants.copy()
shown[labels] = shown[labels].apply(lambda column: '"' + column + '"')
shown

Groups: 161; spellings that are not the commonest: 176, on 3,729 lines
  spaces: 36 spellings, 438 lines
  case: 54 spellings, 1,432 lines
  dash: 5 spellings, 353 lines
  separator: 81 spellings, 1,506 lines
Spellings where both it and its commonest spelling are among the 50 commonest types in training: 2
  "TA Cost AUC ? Non SRN" for "TA Cost AUC – Non SRN"
  "TA Cost AUC / Programme" for "TA Cost AUC - Programme"

,label,commonest spelling,kind,lines,lines in commonest,training rank,training rank (commonest)
0,"""AUC""","""AUC """,spaces,140,334,86,41
1,"""IT SERVICES RUNNING COSTS""","""IT SERVICES RUNNING COSTS""",spaces,70,267,151,48
2,"""Business Rates ""","""Business Rates""",spaces,49,74,194,155
3,"""IT Consultancy ""","""IT Consultancy""",spaces,42,410,208,34
4,"""Service Charges""","""Service Charges """,spaces,29,58,299,196
5,"""RENT ""","""RENT""",spaces,15,817,367,21
6,""" L & P Partner: staffing assistance""","""L & P Partner: staffing assistance""",spaces,11,59,398,172
7,"""RENT ""","""RENT""",spaces,11,817,418,21
8,"""Rent - L&B ""","""Rent - L&B""",spaces,9,10,464,442
9,"""THEORY TEST VARIABLE CHARGES ""","""THEORY TEST VARIABLE CHARGES""",spaces,9,124,466,122
10,""" Environmental Services""","""Environmental Services""",spaces,8,347,468,44
11,"""Property Consultancy ""","""Property Consultancy""",spaces,5,95,564,153
12,"""RENT ""","""RENT""",spaces,5,817,568,21
13,""" Legal Consultancy""","""Legal Consultancy""",spaces,3,608,617,25
14,""" Management Consultancy""","""Management Consultancy""",spaces,3,106,618,110
15,""" Transport Consultancy""","""Transport Consultancy""",spaces,3,13,619,384
16,"""Financial Consultancy ""","""Financial Consultancy""",spaces,3,12,639,434
17,""" Environmental Consultancy""","""Environmental Consultancy""",spaces,2,5,690,547
18,""" IT Consultancy - Other""","""IT Consultancy - Other""",spaces,2,12,691,390
19,""" Programme Partner: staffing assistance""","""Programme Partner: staffing assistance""",spaces,2,244,692,61
20,""" Training & Education""","""Training & Education""",spaces,2,31,693,306
21,""" Agency Personnel""","""Agency Personnel""",spaces,1,42,794,206
22,""" Commercial Partner: Non staffing""","""Commercial Partner: Non staffing""",spaces,1,86,795,279
23,""" Internal Audit""","""Internal Audit""",spaces,1,4,797,645
24,""" L & P Partner: Non staffing""","""L & P Partner: Non staffing""",spaces,1,94,798,189
25,""" Navigational Warnings""","""Navigational Warnings""",spaces,1,4,799,657
26,""" Office Buiding Services Charge""","""Office Buiding Services Charge""",spaces,1,31,800,260
27,""" Other Consultancy""","""Other Consultancy""",spaces,1,86,801,144
28,""" Other Government Entities""","""Other Government Entities""",spaces,1,47,802,270
29,""" Software Licences (Expensed)""","""Software Licences (Expensed)""",spaces,1,45,803,272
30,""" Technical Partner: Non staffing""","""Technical Partner: Non staffing""",spaces,1,132,804,157
31,""" Utilities Design and Delivery""","""Utilities Design and Delivery""",spaces,1,27,805,424
32,"""Agency Personnel ""","""Agency Personnel""",spaces,1,42,811,206
33,"""Facilities Management ""","""Facilities Management""",spaces,1,3,857,638
34,"""Secured Stock ""","""Secured Stock""",spaces,1,24,956,305
35,"""TESTING/TRAINING ""","""TESTING/TRAINING""",spaces,1,26,969,293
36,"""Rent""","""RENT""",case,279,817,55,21
37,"""AGENTS FEES""","""Agents Fees""",case,162,204,80,79
38,"""Other Professional Fees""","""OTHER PROFESSIONAL FEES""",case,129,226,87,66
39,"""Agency Staff Costs""","""AGENCY STAFF COSTS""",case,105,197,137,78
40,"""ELECTRICITY""","""Electricity""",case,101,235,127,72
41,"""Rates""","""RATES""",case,95,236,123,54
42,"""TRAINING""","""Training""",case,71,222,167,73
43,"""RESEARCH""","""Research""",case,67,1393,178,13
44,"""PROPERTY MAINTENANCE""","""Property Maintenance""",case,51,65,198,188
45,"""PURCHASING CARD CHARGES""","""Purchasing Card Charges""",case,39,50,226,190
46,"""Estate Management""","""ESTATE MANAGEMENT""",case,36,83,248,152
47,"""RECRUITMENT""","""Recruitment""",case,35,40,256,257
48,"""SMALL SOFTWARE""","""Small Software""",case,35,201,271,70
49,"""Travel Expenses UK""","""TRAVEL EXPENSES UK""",case,35,35,353,310
50,"""GAS""","""Gas""",case,26,67,312,179
51,"""IT SER RUNNING COSTS""","""IT Ser Running Costs""",case,19,1041,322,18
52,"""OCCUPATIONAL HEALTH SCHEME""","""Occupational Health Scheme""",case,19,54,362,197
53,"""Estate Legal Advisor""","""ESTATE LEGAL ADVISOR""",case,11,22,407,388
54,"""Telephone charges""","""TELEPHONE CHARGES""",case,10,29,536,273
55,"""FURNITURE & FITTINGS""","""Furniture & Fittings""",case,8,15,515,494
56,"""L&B EXCL DWELLINGS""","""L&B Excl Dwellings""",case,8,39,476,247
57,"""CAR TAX & INSURANCE""","""Car Tax & Insurance""",case,6,61,540,170
58,"""MACHINERY MAINTENANCE""","""Machinery Maintenance""",case,6,64,555,162
59,"""P&M CAPITAL COST""","""P&M Capital Cost""",case,6,17,662,497
60,"""Water""","""WATER""",case,6,27,616,288
61,"""Programme and Project Management Consultancy""","""PROGRAMME AND PROJECT MANAGEMENT CONSULTANCY""",case,5,18,563,481
62,"""IT Equipment Capital Cost""","""IT EQUIPMENT CAPITAL COST""",case,4,31,592,282
63,"""Media & Press""","""MEDIA & PRESS""",case,4,6,595,556
64,"""Printing""","""PRINTING""",case,4,9,672,480
65,"""RENT - L&B (NON-PFI)""","""Rent - L&B (non-PFI)""",case,4,151,606,100
66,"""SECONDMENTS""","""Secondments""",case,4,88,609,147
67,"""Building Service Charges""","""BUILDING SERVICE CHARGES""",case,3,42,623,334
68,"""CONFERENCES / SEMINA""","""Conferences / Semina""",case,3,19,706,339
69,"""IT expenses""","""IT Expenses""",case,3,11,644,409
70,"""MANAGEMENT CONSULTANCY""","""Management Consultancy""",case,3,106,650,110
71,"""RECRUITMENT ADVERTISING""","""Recruitment Advertising""",case,3,4,673,676
72,"""TREASURY SOLICITORS""","""Treasury Solicitors""",case,3,35,687,315
73,"""CAR HIRE AND LEASING""","""Car Hire and Leasing""",case,2,9,702,586
74,"""HR CONSULTANCY""","""HR Consultancy""",case,2,29,724,267
75,"""INTERNAL AUDIT FEES""","""Internal Audit Fees""",case,2,12,869,391
76,"""LEGAL CONSULTANCY""","""Legal Consultancy""",case,2,608,<NA>,25
77,"""POSTAGE""","""Postage""",case,2,24,760,349
78,"""TELECOM EQUIPMENT""","""Telecom Equipment""",case,2,7,782,575
79,"""Uniforms""","""UNIFORMS""",case,2,17,791,486
80,"""APPRENTICE LEVY C/A""","""Apprentice Levy C/A""",case,1,22,810,355
81,"""Annual Licences - Tv's""","""Annual Licences - Tv'S""",case,1,3,<NA>,621
82,"""ESTATE LEGAL ADVISORS""","""Estate Legal Advisors""",case,1,6,847,513
83,"""IT EQUIP CAP COST""","""IT Equip Cap Cost""",case,1,85,872,184
84,"""No PO""","""NO PO""",case,1,1,<NA>,896
85,"""Occup Health Scheme""","""OCCUP HEALTH SCHEME""",case,1,1,901,898
86,"""Rent, property service charge, rates""","""Rent, Property Service Charge, Rates""",case,1,2,947,773
87,"""Room Hire""","""ROOM HIRE""",case,1,3,948,942
88,"""SECURITY""","""Security""",case,1,38,950,258
89,"""Veh Hire/Lse st <1yr""","""VEH HIRE/LSE ST <1YR""",case,1,19,983,332
90,"""TA Cost AUC ? Non SRN""","""TA Cost AUC – Non SRN""",dash,325,3915,43,6
91,"""Information Technology (Owned) - Cost – Additions""","""Information Technology (Owned) - Cost - Additions""",dash,24,233,313,60
92,""" IA - Information Technology - Cost – Additions""","""IA - Information Technology - Cost - Additions""",dash,2,28,<NA>,281
93,"""IA - Information Technology - Cost ? Additions""","""IA - Information Technology - Cost - Additions""",dash,1,28,<NA>,281
94,"""Phase 2 Fund ? Health Study ""","""Phase 2 Fund – Health Study """,dash,1,9,928,460
95,"""TA Cost AUC / Programme""","""TA Cost AUC - Programme""",separator,465,19082,26,1
96,"""TA Renewal of Roads / Capital""","""TA Renewal of Roads - Capital""",separator,225,14283,59,2
97,"""Cap Grt Pri Sec/Cos.""","""Cap Grt Pri Sec-Cos.""",separator,126,1539,89,12
98,"""CM / Lump Sum Fees""","""CM - Lump Sum Fees""",separator,97,3498,106,8
99,"""TA Cost AUC / ICT (A)""","""TA Cost AUC - ICT (A)""",separator,92,694,111,20
100,"""TA Renewal of Structures / Capital""","""TA Renewal of Structures - Capital""",separator,71,6559,148,4
101,"""000000 AUC / Phase 1""","""000000 AUC - Phase 1""",separator,63,95,164,108
102,"""AUC / Phase 1""","""AUC - Phase 1""",separator,61,2985,168,9
103,"""Contingent Labour""","""Contingent Labour,""",separator,36,128,430,88
104,"""CurrGrtPriSec/P&NPIS""","""CurrGrtPriSec-P&NPIS""",separator,28,387,276,42
105,"""P40230 / Information Technology""","""P40230 - Information Technology""",separator,26,33,290,251
106,"""P40030 - Land Property""","""P40030 / Land Property""",separator,15,16,364,348
107,"""000000 AUC - Phase 2A""","""000000 AUC / Phase 2A""",separator,12,19,385,320
108,"""CM / Third Party Damage""","""CM - Third Party Damage""",separator,12,661,387,22
109,"""TESTING/TRAINING - CAR HIRE VEHICLE""","""TESTING/TRAINING- CAR HIRE VEHICLE""",separator,11,47,784,238
110,"""IT / Outsource""","""IT - Outsource""",separator,10,519,437,27
111,"""IT Consultancy / Non Rec (DVLA only)""","""IT Consultancy - Non Rec (DVLA only)""",separator,9,17,453,341
112,"""Information Technology (Owned) / Cost / Additions""","""Information Technology (Owned) - Cost - Additions""",separator,9,233,454,60
113,"""P20200 - Phase 2B""","""P20200 / Phase 2B""",separator,9,11,458,414
114,"""Prepaid expenses / admin""","""Prepaid expenses - admin""",separator,9,367,463,35
115,"""P40040 / Human Resources""","""P40040 - Human Resources""",separator,7,11,498,415
116,"""P40019 / Chief Engineer""","""P40019 - Chief Engineer""",separator,6,9,524,459
117,"""RM / Electricity costs""","""RM - Electricity costs""",separator,6,231,527,57
118,"""PROPERTY MAINTENANCE OTHER""","""PROPERTY MAINTENANCE - OTHER""",separator,5,29,560,326
119,"""CM / Time Based Charges""","""CM - Time Based Charges""",separator,4,232,583,74
120,"""CP / Incident Response""","""CP - Incident Response""",separator,4,35,585,254
121,"""P40012 / Quality and Assurance""","""P40012 - Quality and Assurance""",separator,4,8,597,479
122,"""Auc / It Equipment""","""Auc - It Equipment""",separator,3,111,622,112
123,"""Conferences / Exhibitions / Events""","""Conferences/Exhibitions/Events""",separator,3,44,714,214
124,"""Engineering Services / Civil""","""Engineering Services - Civil""",separator,3,250,635,65
125,"""P40010 / Health, Safety & Security""","""P40010 - Health, Safety & Security""",separator,3,6,663,523
126,"""P40210 - Sponsorship""","""P40210 / Sponsorship""",separator,3,4,667,598
127,"""P40700 - Facilities""","""P40700 / Facilities""",separator,3,4,669,599
128,"""Research Grant/PS""","""Research Grant-PS""",separator,3,102,678,129
129,"""000000 Non/CPO L&P Payments""","""000000 Non-CPO L&P Payments""",separator,2,4,694,578
130,"""AUC / Phase 2A""","""AUC - Phase 2A""",separator,2,271,695,49
131,"""Auc / Plant & Machinery""","""Auc - Plant & Machinery""",separator,2,16,699,356
132,"""CG / Vehicles Fuel/Oil""","""CG - Vehicles Fuel/Oil""",separator,2,42,705,241
133,"""CP / Aerial Spraying""","""CP - Aerial Spraying""",separator,2,75,709,165
134,"""CP / Surveillance""","""CP - Surveillance""",separator,2,169,710,82
135,"""Cap Research/CG""","""Cap Research-CG""",separator,2,39,711,296
136,"""Data Supply / TD""","""Data Supply - TD""",separator,2,23,717,317
137,"""IA - Information Technology - Cost Additions""","""IA - Information Technology - Cost - Additions""",separator,2,28,<NA>,281
138,"""IA - Information Technology - Cost – Additions;""","""IA - Information Technology - Cost - Additions""",separator,2,28,<NA>,281
139,"""Other income,""","""Other income""",separator,2,2,746,<NA>
140,"""P30062 / Systems and Stations""","""P30062 - Systems and Stations""",separator,2,2,750,749
141,"""P40037 / Phase Two Commercial""","""P40037 - Phase Two Commercial""",separator,2,3,753,665
142,"""P40200 / Finance""","""P40200 - Finance""",separator,2,3,755,666
143,"""Rent / L&B (non/PFI)""","""Rent - L&B (non-PFI)""",separator,2,151,772,100
144,"""Utilities / Electricity""","""Utilities - Electricity""",separator,2,122,793,105
145,"""000000 Auc / Non Infrastructure""","""000000 Auc - Non Infrastructure""",separator,1,4,807,577
146,"""Auc / Non Infrastructure""","""Auc - Non Infrastructure""",separator,1,32,815,252
147,"""Auc /Int/Licenses""","""Auc -Int-Licenses""",separator,1,1,816,814
148,"""CM / Compensation / Variation Costs""","""CM - Compensation / Variation Costs""",separator,1,117,830,119
149,"""CM / Managing Agent Mobilisation/ De/Mobilisation""","""CM - Managing Agent Mobilisation/ De-Mobilisation""",separator,1,2,831,829
150,"""COS - TRACK AND LAB""","""COS: TRACK AND LAB""",separator,1,5,832,541
151,"""CP / At Sea Equip""","""CP - At Sea Equip""",separator,1,20,834,321
152,"""CP / Flying""","""CP - Flying""",separator,1,141,835,90
153,"""CP / Fuel""","""CP - Fuel""",separator,1,32,836,253
154,"""CapGrtPriSec/P&NPISH""","""CapGrtPriSec-P&NPISH""",separator,1,156,839,149
155,"""Comp S/Ware / Non FA""","""Comp S/Ware - Non FA""",separator,1,81,841,166
156,"""Engineering Services / Systems""","""Engineering Services - Systems""",separator,1,54,852,185
157,"""External Audit Fees / Nao Only""","""External Audit Fees - Nao Only""",separator,1,7,856,550
158,"""Furniture and Fittings (Owned) / Cost / Additions""","""Furniture and Fittings (Owned) - Cost - Additions""",separator,1,12,862,408
159,"""IA / Information Technology / Cost / Additions""","""IA - Information Technology - Cost - Additions""",separator,1,28,867,281
160,"""IT / OTHER""","""IT - OTHER""",separator,1,63,871,183
161,"""Medical Fees / Operational""","""Medical Fees - Operational""",separator,1,14,894,457
162,"""P20150 / Phase 2A""","""P20150 - Phase 2A""",separator,1,1,908,907
163,"""P40021 - Construction Engineering""","""P40021 / Construction Engineering""",separator,1,2,911,751
164,"""P40032 / Procurement & Supply Chain""","""P40032 - Procurement & Supply Chain""",separator,1,1,913,912
165,"""P40033 - Civils and Services - Commercial""","""P40033 / Civils and Services / Commercial""",separator,1,3,914,664
166,"""P40530 / CSE / CCPE / Campaigns, Creative, Projects and Events""","""P40530 - CSE - CCPE - Campaigns, Creative, Projects and Events""",separator,1,3,918,668
167,"""Payroll / Healthcare Cash Plan""","""Payroll - Healthcare Cash Plan""",separator,1,6,926,764
168,"""Payroll / Private Medical ""","""Payroll - Private Medical """,separator,1,32,927,309
169,"""Planned Mtce / Build (Noncap)""","""Planned Mtce - Build (Noncap)""",separator,1,45,929,235
170,"""Plant & Machinery (Owned) / Cost / Additions""","""Plant & Machinery (Owned) - Cost - Additions""",separator,1,90,931,118
171,"""Rent + Property Service Charge""","""Rent & Property Service Charge""",separator,1,1,<NA>,945
172,"""Rent, Property Service Charge""","""Rent & Property Service Charge""",separator,1,1,<NA>,945
173,"""Rent, Property Service Charge ""","""Rent & Property Service Charge""",separator,1,1,946,945
174,"""Rent, Property Service Charge & Rates""","""Rent, Property Service Charge, Rates""",separator,1,2,<NA>,773
175,"""SMarT Funding / MCA""","""SMarT Funding - MCA""",separator,1,47,951,227

**Label variants.** In all, 161 Expense Type labels are spelled more than one way, and 176 spellings are not their label's commonest one, on 3,729 lines. Spaces make 36 of them, such as "RENT" with one, two or three spaces after it, and case makes 54, such as "RESEARCH" for "Research". A dash makes 5, such as the "Non SRN" capital label written with "?" for its dash in April, July and August 2023. A separator makes the other 81, such as "TA Cost AUC / Programme" in August 2022. In 2 pairs both spellings are among the 50 commonest types in training, so one account would count as two kept types. I propose merging every spelling into its commonest one before the kept types are chosen, and listing each merge in Task 3.

In [13]:
def truncation_pairs(
    frame,
    column="Expense Type",
    entity="Entity",
    month="month",
    min_length=10,
):
    """Return pairs of labels where the shorter may be the longer cut short.

    With case and every character that is not a letter or a digit ignored,
    the short label of a pair is at least min_length characters long and is
    the start of the long label, without matching it in full (a full match
    is a spelling variant, not a pair). Blank labels are left out. The rule
    also catches some distinct accounts, such as a general label and a more
    specific one, so every pair needs checking by eye. frame is not changed.

    Parameters
    ----------
    frame : pandas.DataFrame
        One row per line.
    column, entity, month : str
        The label, body and month columns.
    min_length : int, default 10
        The shortest folded label that can be the short side of a pair.

    Returns
    -------
    pandas.DataFrame
        One row per pair: short label, long label, lines (short), lines
        (long), characters (short) once trimmed, shared body (whether any
        body uses both labels) and months (short), the first and last month
        of the short label. Sorted by lines (short), most first.
    """
    lines = frame[frame[column].str.strip() != ""]
    counts = lines[column].value_counts()
    keys = counts.index.str.casefold().str.replace(
        r"[^a-z0-9]", "", regex=True
    )
    folded = pd.Series(keys, index=counts.index)
    folded = folded[folded != ""]
    bodies = {
        label: set(group.str.strip())
        for label, group in lines.groupby(column)[entity]
    }
    first = lines.groupby(column)[month].min()
    last = lines.groupby(column)[month].max()
    rows = []
    for short, short_key in folded.items():
        if len(short_key) < min_length:
            continue
        for long, long_key in folded.items():
            if long_key == short_key or not long_key.startswith(short_key):
                continue
            months = first[short]
            if last[short] != first[short]:
                months = f"{first[short]} to {last[short]}"
            rows.append(
                {
                    "short label": short,
                    "long label": long,
                    "lines (short)": counts[short],
                    "lines (long)": counts[long],
                    "characters (short)": len(short.strip()),
                    "shared body": bool(bodies[short] & bodies[long]),
                    "months (short)": months,
                }
            )
    out = pd.DataFrame(
        rows,
        columns=[
            "short label",
            "long label",
            "lines (short)",
            "lines (long)",
            "characters (short)",
            "shared body",
            "months (short)",
        ],
    )
    out = out.sort_values(
        ["lines (short)", "short label", "long label"],
        ascending=[False, True, True],
    )
    return out.reset_index(drop=True)

In [14]:
pairs = truncation_pairs(df)
shorts = pairs.drop_duplicates("short label")
print(
    f"Candidate pairs: {len(pairs)}; short labels: {len(shorts)}, on "
    f"{shorts['lines (short)'].sum():,} lines"
)
print(
    "Pairs whose short label is exactly 20 characters: "
    f"{(pairs['characters (short)'] == 20).sum()}; pairs that share a body: "
    f"{pairs['shared body'].sum()}"
)
longest = lines.groupby(lines["Entity"].str.strip())["Expense Type"].agg(
    lambda names: names.str.strip().str.len().max()
)
print(
    "Bodies whose longest Expense Type is 20 characters or fewer: "
    + ", ".join(f"{body} ({n})" for body, n in longest[longest <= 20].items())
)

labels = ["short label", "long label"]
shown = pairs.copy()
shown[labels] = shown[labels].apply(lambda column: '"' + column + '"')
shown

Candidate pairs: 241; short labels: 121, on 6,927 lines
Pairs whose short label is exactly 20 characters: 64; pairs that share a body: 132
Bodies whose longest Expense Type is 20 characters or fewer: Active Travel England (20), Department for Transport (20), East West Rail (18)

,short label,long label,lines (short),lines (long),characters (short),shared body,months (short)
0,"""Transport Consult""",""" Transport Consultancy""",1100,3,18,False,2022-04 to 2026-03
1,"""Transport Consult""","""Transport Consultancy""",1100,13,18,False,2022-04 to 2026-03
2,"""Mail Collection/Deli""","""Mail Collection/Delivery Costs""",611,550,20,True,2024-02 to 2026-03
3,"""Legal Consultancy""","""Legal Consultancy / Non Rec (DVLA only)""",608,1,17,True,2022-04 to 2026-03
4,"""Business Services""","""BUSINESS SERVICES DIRECTORATE""",553,3,17,False,2022-04 to 2026-03
5,"""IT Consultancy""",""" IT Consultancy - Other""",410,2,14,True,2022-04 to 2026-03
6,"""IT Consultancy""","""IT Consultancy - Non Rec""",410,12,14,True,2022-04 to 2026-03
7,"""IT Consultancy""","""IT Consultancy - Non Rec (DVLA only)""",410,17,14,True,2022-04 to 2026-03
8,"""IT Consultancy""","""IT Consultancy - Other""",410,12,14,True,2022-04 to 2026-03
9,"""IT Consultancy""","""IT Consultancy / Non Rec (DVLA only)""",410,9,14,True,2022-04 to 2026-03
10,"""Other Professional F""","""OTHER PROFESSIONAL FEE""",247,18,20,False,2022-04 to 2026-03
11,"""Other Professional F""","""OTHER PROFESSIONAL FEES""",247,226,20,False,2022-04 to 2026-03
12,"""Other Professional F""","""Other Professional Fees""",247,129,20,True,2022-04 to 2026-03
13,"""Electricity""","""ELECTRICITY RECHARGES""",235,6,11,False,2022-04 to 2026-03
14,"""Building Service Cha""","""BUILDING SERVICE CHARGE""",176,11,20,False,2022-04 to 2026-03
15,"""Building Service Cha""","""BUILDING SERVICE CHARGES""",176,42,20,False,2022-04 to 2026-03
16,"""Building Service Cha""","""Building Service Charges""",176,3,20,True,2022-04 to 2026-03
17,"""Software Licence Exp""","""Software Licence Expense""",168,176,20,True,2024-02 to 2026-03
18,"""Financial Consultanc""","""Financial Consultancy""",162,12,20,False,2022-04 to 2026-03
19,"""Financial Consultanc""","""Financial Consultancy """,162,3,20,False,2022-04 to 2026-03
20,"""Financial Consultanc""","""Financial Consultancy - Non Rec """,162,1,20,False,2022-04 to 2026-03
21,"""Prepaid expenses""","""Prepaid expenses - admin""",126,367,16,True,2025-04 to 2026-03
22,"""Prepaid expenses""","""Prepaid expenses - programme""",126,16,16,True,2025-04 to 2026-03
23,"""Prepaid expenses""","""Prepaid expenses / admin""",126,9,16,True,2025-04 to 2026-03
24,"""Computer equipment""","""COMPUTER EQUIPMENT S""",122,7,18,False,2022-06 to 2026-03
25,"""Computer equipment""","""COMPUTER EQUIPMENT SERVICE CHARGE""",122,323,18,False,2022-06 to 2026-03
26,"""Computer equipment""","""COMPUTER EQUIPMENT SERVICES""",122,4,18,False,2022-06 to 2026-03
27,"""Government Broker Co""","""Government Broker Costs""",113,65,20,True,2024-02 to 2026-03
28,"""Management Consultan""",""" Management Consultancy""",109,3,20,False,2022-05 to 2026-03
29,"""Management Consultan""","""MANAGEMENT CONSULTANCY""",109,3,20,False,2022-05 to 2026-03
30,"""Management Consultan""","""Management Consultancy""",109,106,20,False,2022-05 to 2026-03
31,"""Management Consultan""","""Management consultancies on admin projects""",109,31,20,False,2022-05 to 2026-03
32,"""ELECTRICITY""","""ELECTRICITY RECHARGES""",101,6,11,True,2022-04 to 2026-03
33,"""Project Management""","""Project Management Consultancy""",96,1,18,False,2022-06 to 2026-03
34,"""Property Consultancy""","""Property Consultancy - Non Rec""",95,1,20,True,2022-06 to 2026-03
35,"""Purchasing Card Char""","""PURCHASING CARD CHARGES""",95,39,20,False,2022-05 to 2026-03
36,"""Purchasing Card Char""","""Purchasing Card Charges""",95,50,20,True,2022-05 to 2026-03
37,"""Machinery Maintenanc""","""MACHINERY MAINTENANCE""",94,6,20,False,2024-02 to 2026-03
38,"""Machinery Maintenanc""","""Machinery Maintenance""",94,64,20,True,2024-02 to 2026-03
39,"""Programme Partner""",""" Programme Partner: staffing assistance""",91,2,17,True,2022-04 to 2023-01
40,"""Programme Partner""","""Programme Partner: Non staffing""",91,37,17,True,2022-04 to 2023-01
41,"""Programme Partner""","""Programme Partner: staffing assistance""",91,244,17,True,2022-04 to 2023-01
42,"""SUBCONTRACTED SERVICE""","""SUBCONTRACTED SERVICES""",77,12,21,True,2022-12 to 2026-03
43,"""Non-stock Printing""","""Non-stock Printing Purchases""",74,35,18,True,2024-02 to 2026-03
44,"""Non Stock Machine Co""","""Non Stock Machine Consumables""",68,66,20,True,2024-02 to 2026-03
45,"""GR/IR Secured Stock""","""GR/IR Secured Stock Clearing Account""",66,1,20,True,2024-02 to 2026-03
46,"""Medical Advisory Ser""","""Medical Advisory Service""",66,24,20,True,2022-08 to 2026-03
47,"""Property Maintenance""","""PROPERTY MAINTENANCE - OTHER""",65,29,20,False,2022-04 to 2026-03
48,"""Property Maintenance""","""PROPERTY MAINTENANCE OTHER""",65,5,20,False,2022-04 to 2026-03
49,"""Estates PFI Unitary""","""Estates PFI Unitary Service Charge""",61,51,19,True,2024-02 to 2026-03
50,"""Infrastructure Maint""","""Infrastructure Maintenance""",56,2,20,True,2022-05 to 2026-03
51,"""THEORY TEST VARIABLE CHARGE""","""THEORY TEST VARIABLE CHARGES""",53,124,27,True,2023-03 to 2024-05
52,"""THEORY TEST VARIABLE CHARGE""","""THEORY TEST VARIABLE CHARGES """,53,9,27,True,2023-03 to 2024-05
53,"""PROPERTY MAINTENANCE""","""PROPERTY MAINTENANCE - OTHER""",51,29,20,True,2022-04 to 2026-03
54,"""PROPERTY MAINTENANCE""","""PROPERTY MAINTENANCE OTHER""",51,5,20,True,2022-04 to 2026-03
55,"""Legal advice""","""Legal Advice and Fees""",50,3,12,False,2022-04 to 2025-12
56,"""Non-CPO L&P Payments""","""Non-CPO L&P Payments HS2""",49,24,20,True,2022-04 to 2024-09
57,"""Non Secured stock""","""Non Secured stock clearing account""",43,57,17,True,2022-04 to 2023-03
58,"""IT Consultancy """,""" IT Consultancy - Other""",42,2,14,False,2023-06 to 2024-01
59,"""IT Consultancy ""","""IT Consultancy - Non Rec""",42,12,14,True,2023-06 to 2024-01
60,"""IT Consultancy ""","""IT Consultancy - Non Rec (DVLA only)""",42,17,14,True,2023-06 to 2024-01
61,"""IT Consultancy ""","""IT Consultancy - Other""",42,12,14,False,2023-06 to 2024-01
62,"""IT Consultancy ""","""IT Consultancy / Non Rec (DVLA only)""",42,9,14,True,2023-06 to 2024-01
63,"""PROTECTIVE CLOTHING""","""Protective clothing & uniforms""",42,51,19,False,2022-04 to 2024-10
64,"""Recruitment""","""RECRUITMENT ADVERTISEMENT""",40,7,11,False,2022-06 to 2026-03
65,"""Recruitment""","""RECRUITMENT ADVERTISING""",40,3,11,False,2022-06 to 2026-03
66,"""Recruitment""","""RECRUITMENT ADVERTISMENT""",40,1,11,False,2022-06 to 2026-03
67,"""Recruitment""","""Recruitment - Pre-employment checks""",40,1,11,False,2022-06 to 2026-03
68,"""Recruitment""","""Recruitment Advertis""",40,7,11,True,2022-06 to 2026-03
69,"""Recruitment""","""Recruitment Advertising""",40,4,11,False,2022-06 to 2026-03
70,"""Recruitment""","""Recruitment Advertising / Publicity""",40,49,11,False,2022-06 to 2026-03
71,"""Recruitment""","""Recruitment Costs""",40,3,11,False,2022-06 to 2026-03
72,"""Recruitment""","""Recruitment Fees""",40,273,11,True,2022-06 to 2026-03
73,"""Recruitment""","""Recruitment consultancies / Non/Executive""",40,1,11,False,2022-06 to 2026-03
74,"""Office Accommodation""","""Office Accommodation (Rent)""",37,9,20,False,2022-04 to 2024-04
75,"""RECRUITMENT""","""RECRUITMENT ADVERTISEMENT""",35,7,11,True,2022-05 to 2026-01
76,"""RECRUITMENT""","""RECRUITMENT ADVERTISING""",35,3,11,True,2022-05 to 2026-01
77,"""RECRUITMENT""","""RECRUITMENT ADVERTISMENT""",35,1,11,True,2022-05 to 2026-01
78,"""RECRUITMENT""","""Recruitment - Pre-employment checks""",35,1,11,False,2022-05 to 2026-01
79,"""RECRUITMENT""","""Recruitment Advertis""",35,7,11,False,2022-05 to 2026-01
80,"""RECRUITMENT""","""Recruitment Advertising""",35,4,11,False,2022-05 to 2026-01
81,"""RECRUITMENT""","""Recruitment Advertising / Publicity""",35,49,11,False,2022-05 to 2026-01
82,"""RECRUITMENT""","""Recruitment Costs""",35,3,11,False,2022-05 to 2026-01
83,"""RECRUITMENT""","""Recruitment Fees""",35,273,11,False,2022-05 to 2026-01
84,"""RECRUITMENT""","""Recruitment consultancies / Non/Executive""",35,1,11,False,2022-05 to 2026-01
85,"""Machine Consumables""","""Machine Consumables Stock Balance""",34,1,19,True,2022-04 to 2025-10
86,"""TECHNICAL SERVICES SUPPORT""","""TECHNICAL SERVICES SUPPORT (TSS)""",28,1,26,True,2023-06 to 2023-12
87,"""Agency Staff""","""AGENCY STAFF COSTS""",27,197,12,False,2022-04 to 2026-03
88,"""Agency Staff""","""Agency Staff Costs""",27,105,12,False,2022-04 to 2026-03
89,"""TESTING/TRAINING""","""TESTING/TRAINING - CAR HIRE VEHICLE""",26,11,16,True,2022-10 to 2023-12
90,"""TESTING/TRAINING""","""TESTING/TRAINING - M""",26,1,16,True,2022-10 to 2023-12
91,"""TESTING/TRAINING""","""TESTING/TRAINING - MOTORCYCLE""",26,1,16,True,2022-10 to 2023-12
92,"""TESTING/TRAINING""","""TESTING/TRAINING - MOTORCYCLE HIRE""",26,15,16,True,2022-10 to 2023-12
93,"""TESTING/TRAINING""","""TESTING/TRAINING - VEHICLE HIRE""",26,1,16,True,2022-10 to 2023-12
94,"""TESTING/TRAINING""","""TESTING/TRAINING- CA""",26,1,16,True,2022-10 to 2023-12
95,"""TESTING/TRAINING""","""TESTING/TRAINING- CAR""",26,2,16,True,2022-10 to 2023-12
96,"""TESTING/TRAINING""","""TESTING/TRAINING- CAR HIRE VEHICLE""",26,47,16,True,2022-10 to 2023-12
97,"""It Services""","""IT SERVICES RUNNING COSTS""",24,267,11,False,2022-04 to 2024-03
98,"""It Services""","""IT SERVICES RUNNING COSTS""",24,70,11,False,2022-04 to 2024-03
99,"""Secured Stock""","""Secured Stock Clearing Account""",24,19,13,True,2022-04 to 2023-03
100,"""Commercial Partner""",""" Commercial Partner: Non staffing""",23,1,18,True,2022-04 to 2022-11
101,"""Commercial Partner""","""Commercial Partner: Non staffing""",23,86,18,True,2022-04 to 2022-11
102,"""Commercial Partner""","""Commercial Partner: staffing assistance""",23,103,18,True,2022-04 to 2022-11
103,"""ESTATE LEGAL ADVISOR""","""ESTATE LEGAL ADVISORS""",22,1,20,True,2023-02 to 2026-03
104,"""ESTATE LEGAL ADVISOR""","""Estate Legal Advisors""",22,6,20,False,2023-02 to 2026-03
105,"""Conferences / Semina""","""CONFERENCES / SEMINAR""",19,6,20,False,2022-08 to 2025-08
106,"""Conferences / Semina""","""CONFERENCES / SEMINARS/VENUE HIRE""",19,2,20,False,2022-08 to 2025-08
107,"""Conferences / Semina""","""Conferences/Seminars""",19,10,20,False,2022-08 to 2025-08
108,"""Training Costs""","""Training Costs Police""",19,5,14,True,2022-05 to 2025-05
109,"""Legal Costs""","""LEGAL COSTS - PROSECUTION""",18,1,11,False,2024-02 to 2026-02
110,"""Legal Costs""","""Legal Costs Defence""",18,2,11,False,2024-02 to 2026-02
111,"""OTHER PROFESSIONAL FEE""","""OTHER PROFESSIONAL FEES""",18,226,22,True,2024-01 to 2024-03
112,"""OTHER PROFESSIONAL FEE""","""Other Professional Fees""",18,129,22,False,2024-01 to 2024-03
113,"""Pensions Other""","""Pensions Other - Er""",15,15,14,True,2022-04 to 2023-09
114,"""Procurement Consul""","""Procurement Consultancy""",15,1,18,False,2022-08 to 2026-03
115,"""Subscriptions to Pro""","""Subscriptions to professional or learned societies""",14,8,20,False,2023-04 to 2026-03
116,"""Technical Partners""","""Technical Partner: staffing assistance""",13,76,18,True,2022-04 to 2022-09
117,"""Vehicle Hire""","""VEHICLE HIRE/LEASE ST <1YR""",13,29,12,False,2022-06 to 2025-12
118,"""Financial Consultancy""","""Financial Consultancy - Non Rec """,12,1,21,True,2022-05 to 2025-10
119,"""IT Consultancy - Non Rec""","""IT Consultancy - Non Rec (DVLA only)""",12,17,24,True,2023-08
120,"""IT Consultancy - Non Rec""","""IT Consultancy / Non Rec (DVLA only)""",12,9,24,True,2023-08
121,"""Internal Audit Fees""","""Internal Audit Fees for 23-24""",12,1,19,False,2022-04 to 2025-04
122,"""BUILDING SERVICE CHARGE""","""BUILDING SERVICE CHARGES""",11,42,23,True,2022-04 to 2024-03
123,"""BUILDING SERVICE CHARGE""","""Building Service Charges""",11,3,23,False,2022-04 to 2024-03
124,"""CONTINUOUS IMP""","""CONTINUOUS IMPROVEMENT""",11,16,14,True,2025-08 to 2025-12
125,"""DfT Reimbursement – Property Management – 1ES""","""DfT Reimbursement – Property Management – 1ES Prior Year""",11,6,45,True,2024-02 to 2026-02
126,"""Estate Legal Advisor""","""ESTATE LEGAL ADVISORS""",11,1,20,False,2024-04 to 2025-03
127,"""Estate Legal Advisor""","""Estate Legal Advisors""",11,6,20,True,2024-04 to 2025-03
128,"""Temporary staff""","""Temporary Staff Police""",11,2,15,False,2024-03 to 2024-10
129,"""Temporary staff""","""Temporary Staff Staff""",11,2,15,False,2024-03 to 2024-10
130,"""Conferences/Seminars""","""CONFERENCES / SEMINARS/VENUE HIRE""",10,2,20,False,2024-10 to 2026-03
131,"""Hire Of Premises""","""Hire Of Premises For Training""",10,1,16,True,2022-06 to 2026-03
132,"""SOFTWARE LICENCES CAPITAL COST""","""SOFTWARE LICENCES CAPITAL COST (INTANGIBLE)""",10,168,30,True,2024-02
133,"""CP - Dispersant""","""CP - Dispersant Storage and Maintenance""",8,1,15,True,2022-07 to 2026-02
134,"""Consultancy""","""Consultancy Charges""",8,2,11,False,2022-05
135,"""Consultancy""","""Consultancy Fees - Training & Development""",8,3,11,False,2022-05
136,"""IT - HARDWARE""","""It Hardware Maintenance""",8,71,13,False,2025-08 to 2025-12
137,"""IT - HARDWARE""","""It Hardware Purch (Noncap)""",8,11,13,False,2025-08 to 2025-12
138,"""SOFTWARE LICENCE CAP""","""SOFTWARE LICENCE CAPITAL""",8,8,20,True,2024-03
139,"""COMPUTER EQUIPMENT S""","""COMPUTER EQUIPMENT SERVICE CHARGE""",7,323,20,True,2024-04
140,"""COMPUTER EQUIPMENT S""","""COMPUTER EQUIPMENT SERVICES""",7,4,20,True,2024-04
141,"""External Audit""","""External Audit (Cash)""",7,6,14,False,2023-03 to 2026-02
142,"""External Audit""","""External Audit Fees - Nao Only""",7,7,14,False,2023-03 to 2026-02
143,"""External Audit""","""External Audit Fees / Nao Only""",7,1,14,False,2023-03 to 2026-02
144,"""Recruitment Advertis""","""RECRUITMENT ADVERTISEMENT""",7,7,20,False,2022-10 to 2025-07
145,"""Recruitment Advertis""","""RECRUITMENT ADVERTISING""",7,3,20,False,2022-10 to 2025-07
146,"""Recruitment Advertis""","""RECRUITMENT ADVERTISMENT""",7,1,20,False,2022-10 to 2025-07
147,"""Recruitment Advertis""","""Recruitment Advertising""",7,4,20,False,2022-10 to 2025-07
148,"""Recruitment Advertis""","""Recruitment Advertising / Publicity""",7,49,20,False,2022-10 to 2025-07
149,"""CONFERENCES / SEMINAR""","""CONFERENCES / SEMINARS/VENUE HIRE""",6,2,21,True,2023-11 to 2026-01
150,"""CONFERENCES / SEMINAR""","""Conferences/Seminars""",6,10,21,False,2023-11 to 2026-01
151,"""Exhibitions""","""Exhibitions and Demonstrations""",6,7,11,False,2022-08 to 2024-11
152,"""TECHNICAL SERVICE SUPPORT""","""TECHNICAL SERVICE SUPPORT (TSS)""",6,8,25,True,2023-03 to 2023-04
153,"""TTEST VAR CHARGE""","""TTEST VAR CHARGE-CAR""",6,5,16,True,2022-05 to 2023-02
154,"""IT Software""","""It Software Maintenance""",5,94,11,False,2022-07 to 2022-10
155,"""IT Software""","""It Software Purch (Noncap)""",5,42,11,False,2022-07 to 2022-10
156,"""Property Consultancy ""","""Property Consultancy - Non Rec""",5,1,20,True,2023-06 to 2023-11
157,"""Technical Partner""",""" Technical Partner: Non staffing""",5,1,17,True,2022-11 to 2023-01
158,"""Technical Partner""","""Technical Partner: Non staffing""",5,132,17,True,2022-11 to 2023-01
159,"""Technical Partner""","""Technical Partner: staffing assistance""",5,76,17,True,2022-11 to 2023-01
160,"""Technical Partner""","""Technical Partners""",5,13,17,True,2022-11 to 2023-01
161,"""Internal Audit""","""INTERNAL AUDIT FEES""",4,2,14,False,2023-04 to 2026-03
162,"""Internal Audit""","""Internal Audit Fees""",4,12,14,False,2023-04 to 2026-03
163,"""Internal Audit""","""Internal Audit Fees for 23-24""",4,1,14,True,2023-04 to 2026-03
164,"""PERIODICALS & SUBS""","""PERIODICALS & SUBSCRIPTIONS""",4,6,18,True,2023-06 to 2024-11
165,"""Recruitment Advertising""","""Recruitment Advertising / Publicity""",4,49,23,False,2023-04 to 2025-12
166,""" Legal Consultancy""","""Legal Consultancy / Non Rec (DVLA only)""",3,1,17,False,2022-12 to 2025-03
167,"""CONFERENCES / SEMINA""","""CONFERENCES / SEMINAR""",3,6,20,True,2024-10 to 2025-10
168,"""CONFERENCES / SEMINA""","""CONFERENCES / SEMINARS/VENUE HIRE""",3,2,20,True,2024-10 to 2025-10
169,"""CONFERENCES / SEMINA""","""Conferences/Seminars""",3,10,20,False,2024-10 to 2025-10
170,"""Engineering Services""","""Engineering Services - Civil""",3,250,20,False,2022-07 to 2024-04
171,"""Engineering Services""","""Engineering Services - Systems""",3,54,20,False,2022-07 to 2024-04
172,"""Engineering Services""","""Engineering Services / Civil""",3,3,20,False,2022-07 to 2024-04
173,"""Engineering Services""","""Engineering Services / Systems""",3,1,20,False,2022-07 to 2024-04
174,"""Facilities Management""","""Facilities Management Charges""",3,146,21,False,2022-04
175,"""Facilities Management""","""Facilities Management Reactive Works""",3,132,21,False,2022-04
176,"""Facilities Management""","""Facilities Management Rective Works""",3,2,21,False,2022-04
177,"""Financial Consultancy ""","""Financial Consultancy - Non Rec """,3,1,21,True,2022-04 to 2024-01
178,"""Leasehold Improvements""","""Leasehold Improvements - Cost Additions""",3,1,22,True,2024-04 to 2024-05
179,"""RECRUITMENT ADVERTISING""","""Recruitment Advertising / Publicity""",3,49,23,False,2022-08 to 2022-12
180,"""Subscriptions""","""Subscriptions to Pro""",3,14,13,False,2023-12 to 2025-11
181,"""Subscriptions""","""Subscriptions to professional or learned societies""",3,8,13,False,2023-12 to 2025-11
182,"""BUILDING WORKS CAP""","""BUILDING WORKS CAPITAL""",2,1,18,True,2024-04
183,"""BUILDING WORKS CAP""","""BUILDING WORKS CAPITAL COSTS""",2,40,18,True,2024-04
184,"""INTERNAL AUDIT FEES""","""Internal Audit Fees for 23-24""",2,1,19,False,2023-10 to 2025-10
185,"""LEGAL CONSULTANCY""","""Legal Consultancy / Non Rec (DVLA only)""",2,1,17,False,2026-01 to 2026-02
186,"""OFFICE EQUIPMENT (NON-CAP)""","""OFFICE EQUIPMENT (NON-CAPITAL)""",2,9,26,True,2022-11 to 2023-11
187,"""P40300 - Legal""","""P40300 / Legal, Counter Fraud & Insurance""",2,2,14,True,2022-05
188,"""Printing Stock Balan""","""Printing Stock Balances""",2,2,20,True,2026-02
189,"""SUBCONTRACTED SERVIC""","""SUBCONTRACTED SERVICE""",2,77,20,True,2022-07 to 2024-04
190,"""SUBCONTRACTED SERVIC""","""SUBCONTRACTED SERVICES""",2,12,20,True,2022-07 to 2024-04
191,"""Software Licenses""","""Software Licenses Expense""",2,1,17,True,2022-09 to 2023-08
192,"""TESTING/TRAINING- CAR""","""TESTING/TRAINING - CAR HIRE VEHICLE""",2,11,21,True,2024-11
193,"""TESTING/TRAINING- CAR""","""TESTING/TRAINING- CAR HIRE VEHICLE""",2,47,21,True,2024-11
194,""" Internal Audit""","""INTERNAL AUDIT FEES""",1,2,14,False,2025-03
195,""" Internal Audit""","""Internal Audit Fees""",1,12,14,False,2025-03
196,""" Internal Audit""","""Internal Audit Fees for 23-24""",1,1,14,True,2025-03
197,"""Accommodation""","""Accommodation project equipment""",1,3,13,False,2026-01
198,"""BUILDING WORKS CAPITAL""","""BUILDING WORKS CAPITAL COSTS""",1,40,22,True,2024-01
199,"""CAR PARKING""","""Car Parking Fees""",1,3,11,False,2022-04
200,"""Early Retirement Provision""","""Early Retirement Provision - Expense AME""",1,1,26,True,2023-02
201,"""Facilities Management ""","""Facilities Management Charges""",1,146,21,False,2024-03
202,"""Facilities Management ""","""Facilities Management Reactive Works""",1,132,21,False,2024-03
203,"""Facilities Management ""","""Facilities Management Rective Works""",1,2,21,False,2024-03
204,"""Interpreter""","""Interpreters Fees""",1,5,11,False,2025-05
205,"""Prop Maitenance Oth""","""PROP MAITENANCE OTHER""",1,2,19,False,2022-05
206,"""Property Service Charge""","""Property Service Charge & Rent""",1,2,23,True,2023-04
207,"""RADIO LICENCE""","""Radio Licence Fees""",1,8,13,False,2022-07
208,"""Rent & Property Service Charge""","""Rent, Property Service Charge & Rates""",1,1,30,True,2024-11
209,"""Rent & Property Service Charge""","""Rent, Property Service Charge, Rates""",1,2,30,True,2024-11
210,"""Rent & Property Service Charge""","""Rent, property service charge, rates""",1,1,30,True,2024-11

**Truncation pairs.** The prefix rule finds 241 candidate pairs, with 121 short labels on 6,927 lines. Some are a label cut short, such as "Mail Collection/Deli" from February 2024 for "Mail Collection/Delivery Costs". Others are distinct accounts, such as "IT Consultancy" and "IT Consultancy - Non Rec", so I list every pair for a check by eye before any merge. The short label is exactly 20 characters in 64 pairs. The Department for Transport and Active Travel England never use a label longer than 20 characters, which suggests their system cuts labels at 20. So I also flag every label of exactly 20 characters in the anomaly list.

In [15]:
def labels_new_at_body(
    frame,
    body,
    prefix,
    since,
    column="Expense Type",
    entity="Entity",
    month="month",
    split="split",
):
    """Return the labels a body began to use from a given month.

    A label is listed when, once runs of spaces are closed up, it starts
    with prefix, and the body (the trimmed entity) uses it from since
    onwards but never before. Its first month and its lines in each split
    count every body's lines. Its status is "in training" when the training
    split holds at least one of its lines, and "first seen after training"
    otherwise. frame is not changed.

    Parameters
    ----------
    frame : pandas.DataFrame
        One row per line, with a split column.
    body : str
        The body, as the trimmed entity.
    prefix : str
        The start every listed label shares.
    since : str
        The month, "YYYY-MM", from which the body uses each label.
    column, entity, month, split : str
        The label, body, month and split columns.

    Returns
    -------
    pandas.DataFrame
        Indexed by label as published, in label order: first month,
        training, validation, test and status.
    """
    lines = frame[frame[column].str.strip() != ""]
    closed = lines[column].str.replace(r"\s+", " ", regex=True).str.strip()
    at_body = lines[
        (lines[entity].str.strip() == body) & closed.str.startswith(prefix)
    ]
    before = set(at_body.loc[at_body[month] < since, column])
    new = sorted(set(at_body.loc[at_body[month] >= since, column]) - before)
    chosen = lines[lines[column].isin(new)]
    splits = ["training", "validation", "test"]
    table = pd.DataFrame(
        {
            name: chosen[chosen[split] == name][column].value_counts()
            for name in splits
        },
        index=new,
    )
    table = table.fillna(0).astype(int)
    table.insert(0, "first month", chosen.groupby(column)[month].min())
    table["status"] = np.where(
        table["training"] > 0, "in training", "first seen after training"
    )
    return table

In [16]:
new_labels = labels_new_at_body(
    df, body="National Highways", prefix="TA Cost AUC", since="2025-04"
)
in_training = (new_labels["status"] == "in training").sum()
by_split = new_labels[["training", "validation", "test"]].sum()
print(
    f"{len(new_labels)} labels: {in_training} in training, "
    f"{len(new_labels) - in_training} first seen after training; lines: "
    f"training {by_split['training']:,}, validation "
    f"{by_split['validation']:,}, test {by_split['test']:,}"
)
test_lines = (lines["split"] == "test").sum()
print(f"Share of test lines: {by_split['test'] / test_lines:.1%}")
new_labels

15 labels: 12 in training, 3 first seen after training; lines: training 34, validation 185, test 2,091
Share of test lines: 12.8%

                                           first month  training  validation  test                     status
TA  Cost AUC                                   2026-03         0           0    19  first seen after training
TA Cost AUC - Ancillaries                      2025-06         2          23   148                in training
TA Cost AUC - Capitalisable Pay                2026-01         0           0     1  first seen after training
TA Cost AUC - Design Services                  2025-05         6          19   225                in training
TA Cost AUC - Drainage                         2025-04         2          15   148                in training
TA Cost AUC - Geotechnics                      2025-06         1           4    27                in training
TA Cost AUC - Lighting                         2025-06         1          12   137                in training
TA Cost AUC - Pavements Flexible               2025-05         1          15   279                in training
TA Cost AUC - Pavements Rigid                  2025-08         0           1    15  first seen after training
TA Cost AUC - Road Restraints                  2025-06         5          18   149                in training
TA Cost AUC - Roadside Tech                    2025-06         1           9   109                in training
TA Cost AUC - Soft Estates                     2025-06         1           4    75                in training
TA Cost AUC - Structures                       2025-04         7          19   222                in training
TA Cost AUC - Tech Survey and Testing          2025-05         3          16    88                in training
TA Cost AUC - Temporary Traffic Management     2025-06         4          30   449                in training

**The 2025 National Highways labels.** From April 2025 National Highways began to use 15 "TA Cost AUC" labels, such as "TA Cost AUC - Temporary Traffic Management". Of the 15, 12 appear in the training months, but rarely: 34 lines between them. The other 3 are novel classes, first seen after the training months: "TA Cost AUC - Pavements Rigid" from August 2025, "TA Cost AUC - Capitalisable Pay" in January 2026, and "TA  Cost AUC", published with two spaces, in March 2026. Validation holds 185 of their lines and test 2,091, which is 12.8% of the test lines. I keep them in the test months and report them as found.

In [17]:
def flag_anomalies(
    frame,
    variants,
    pairs,
    new_labels,
    published,
    cp850_files,
    drift_files,
    placeholders,
    hs2,
    hs2_labels,
    ewr,
    rare_body_lines=10,
    top_share=0.001,
    threshold=25_000,
):
    """Return one True or False column per kind of anomaly, for every row.

    A blank row (every published cell empty) is flagged as blank_row and
    nothing else. Every other kind looks only at lines with content. The
    kinds, in column order:

    - blank_row; cp850_file and header_drift: the line comes from one of
      cp850_files or drift_files;
    - spreadsheet_error: a cell holds "#N/A" or "N/A";
    - date_not_dd_mm_yyyy: the date is not written as dd/mm/yyyy;
    - date_outside_month: the date falls outside the file's month;
    - amount_unreadable, below_threshold, at_threshold: no amount, an
      amount under threshold, or exactly threshold;
    - very_large: the amount is in the top top_share of lines;
    - family_variant: Department Family is not its commonest spelling;
    - entity_spaces: Entity has spaces round it;
    - ewr: the trimmed Entity is one of the names in ewr;
    - rare_body: the trimmed Entity has fewer than rare_body_lines lines;
    - redacted: the Supplier contains "redact";
    - placeholder: the Supplier, in capitals, matches placeholders;
    - supplier_variant: the Supplier is not the commonest name among
      names that match once in capitals, with every character that is not
      a letter or a digit removed and a final LIMITED, LTD, PLC or LLP
      dropped (a tie goes to the name that sorts first);
    - exact_duplicate: every published cell repeats an earlier line;
    - near_duplicate: the line shares its Supplier, amount, date and
      Transaction No with another line that differs elsewhere;
    - split_transaction: its trimmed Transaction No carries more than one
      Expense Type in one body ("#", "N/A" and blank are not numbers);
    - no_transaction_number, no_item_text: "#", "N/A" or blank, and for
      Item Text also "##" and "#N/A";
    - label_20: the trimmed Expense Type is exactly 20 characters;
    - variant_spaces, variant_case, variant_dash, variant_separator: the
      Expense Type is a spelling of that kind in variants;
    - truncation: the Expense Type is a short label in pairs;
    - hs2_auc: an hs2 line whose label, spaces closed up, is in hs2_labels;
    - nh_2025: the Expense Type is in new_labels' index;
    - unseen_type: a validation or test line whose Expense Type never
      occurs in training.

    frame is not changed and no row is removed.

    Returns
    -------
    pandas.DataFrame
        One bool column per kind, in the order above, on frame's index.
    """
    trimmed = frame[published].apply(lambda column: column.str.strip())
    content = trimmed.ne("").any(axis=1)
    entity = trimmed["Entity"]
    label = frame["Expense Type"]
    closed = label.str.replace(r"\s+", " ", regex=True).str.strip()
    supplier = frame["Supplier"]
    number = trimmed["Transaction No"]
    amount = frame["amount"]

    families = frame.loc[content, "Department Family"].value_counts()
    bodies = entity[content].value_counts()
    cut = amount[content].quantile(1 - top_share)

    key = supplier.str.upper().str.replace(r"[^A-Z0-9]", "", regex=True)
    key = key.str.replace(r"(LIMITED|LTD|PLC|LLP)$", "", regex=True)
    names = pd.DataFrame({"key": key, "name": supplier})[content]
    names = names.value_counts().rename("lines").reset_index()
    names = names.sort_values(["lines", "name"], ascending=[False, True])
    commonest = names.groupby("key")["name"].first()
    shared = names.groupby("key")["name"].size() > 1
    shared_keys = shared.index[shared]

    rows = frame.loc[content, published + ["amount", "date"]]
    near_key = ["Supplier", "amount", "date", "Transaction No"]
    group = rows.groupby(near_key, dropna=False).ngroup()
    distinct = rows.assign(group=group).drop_duplicates(published)
    distinct = distinct.groupby("group").size()
    near = (group.map(group.value_counts()) > 1) & (group.map(distinct) > 1)

    numbered = content & ~number.isin(["", "#", "N/A"])
    types = pd.DataFrame(
        {"body": entity, "number": number, "label": label.str.strip()}
    )[numbered]
    types = types.groupby(["body", "number"])["label"].transform("nunique")

    in_training = content & (frame["split"] == "training")
    kind_of = variants.set_index("label")["kind"]

    flags = {
        "blank_row": ~content,
        "cp850_file": frame["source_file"].isin(cp850_files),
        "header_drift": frame["source_file"].isin(drift_files),
        "spreadsheet_error": trimmed.isin(["#N/A", "N/A"]).any(axis=1),
        "date_not_dd_mm_yyyy": ~frame["Date"].str.fullmatch(
            r"\d{2}/\d{2}/\d{4}"
        ),
        "date_outside_month": frame["date"].notna()
        & (frame["date"].dt.strftime("%Y-%m") != frame["month"]),
        "amount_unreadable": amount.isna(),
        "below_threshold": amount < threshold,
        "at_threshold": amount == threshold,
        "very_large": amount >= cut,
        "family_variant": frame["Department Family"] != families.index[0],
        "entity_spaces": frame["Entity"] != entity,
        "ewr": entity.isin(ewr),
        "rare_body": entity.map(bodies) < rare_body_lines,
        "redacted": supplier.str.contains("redact", case=False),
        "placeholder": supplier.str.upper().str.contains(placeholders),
        "supplier_variant": key.isin(shared_keys)
        & (supplier != key.map(commonest)),
        "exact_duplicate": frame.duplicated(published, keep="first"),
        "near_duplicate": near.reindex(frame.index, fill_value=False),
        "split_transaction": (types > 1).reindex(
            frame.index, fill_value=False
        ),
        "no_transaction_number": number.isin(["", "#", "N/A"]),
        "no_item_text": trimmed["Item Text"].isin(
            ["", "#", "##", "#N/A", "N/A"]
        ),
        "label_20": label.str.strip().str.len() == 20,
    }
    for kind in ("spaces", "case", "dash", "separator"):
        flags[f"variant_{kind}"] = label.isin(kind_of.index[kind_of == kind])
    flags["truncation"] = label.isin(pairs["short label"])
    flags["hs2_auc"] = (entity == hs2) & closed.isin(hs2_labels)
    flags["nh_2025"] = label.isin(new_labels.index)
    flags["unseen_type"] = (frame["split"] != "training") & ~label.isin(
        label[in_training]
    )
    out = pd.DataFrame(flags, index=frame.index).astype(bool)
    out.loc[~content] = False
    out["blank_row"] = ~content
    return out

In [18]:
def anomaly_table(frame, flags, kinds, amount="amount"):
    """Return the anomaly list: the lines and value of each kind.

    For each kind the list gives the lines flagged, their value, the
    published total with them, and the total without them. A line can be
    flagged for several kinds, so the rows do not add up to the file. No
    ruling is made here, so every ruling reads "for Paddy to rule". None of
    the inputs is changed.

    Parameters
    ----------
    frame : pandas.DataFrame
        One row per line, with an amount column.
    flags : pandas.DataFrame
        One bool column per kind, on frame's index.
    kinds : pandas.DataFrame
        Indexed by kind, in the same order as flags' columns: anomaly, the
        description, and proposed treatment.
    amount : str, default "amount"
        The amount column, in pounds.

    Returns
    -------
    pandas.DataFrame
        Numbered from 1, one row per kind: anomaly, lines, £ in these
        lines, total £ with them, total £ without them, proposed treatment
        and ruling.

    Raises
    ------
    ValueError
        If kinds does not list flags' columns in the same order.
    """
    if list(kinds.index) != list(flags.columns):
        raise ValueError("kinds must list the flag columns in the same order")
    total = frame[amount].sum()
    value = np.array(
        [frame.loc[flags[kind], amount].sum() for kind in flags.columns]
    )
    return pd.DataFrame(
        {
            "anomaly": kinds["anomaly"].to_numpy(),
            "lines": flags.sum().to_numpy(),
            "£ in these lines": value,
            "total £ with them": total,
            "total £ without them": total - value,
            "proposed treatment": kinds["proposed treatment"].to_numpy(),
            "ruling": "for Paddy to rule",
        },
        index=pd.RangeIndex(1, len(kinds) + 1, name="#"),
    )

In [19]:
# My proposed treatment for each kind: flag it (mark the lines and keep
# them), keep it (no action), or exclude it (leave the lines out of
# modelling, while the raw data keeps them). rare_body_lines is my own
# assumed limit, not a rule from the data.
rare_body_lines = 10
months_held = df["month"].nunique()
kinds = pd.DataFrame.from_records(
    [
        (
            "blank_row",
            "Blank row: every published cell empty",
            "exclude: no content",
        ),
        (
            "cp850_file",
            f"Line from one of the {len(cp850_files)} files that store £ as "
            "byte 0x9C (cp850)",
            "keep: the build reads them as cp850, so every amount is right",
        ),
        (
            "header_drift",
            f"Line from one of the {len(drift_files)} files that name a "
            "column differently",
            "keep: the build maps the names",
        ),
        (
            "spreadsheet_error",
            'Cell holding the spreadsheet error "#N/A" or "N/A"',
            "keep: treat the cell as missing",
        ),
        (
            "date_not_dd_mm_yyyy",
            "Date not written dd/mm/yyyy: dots, or spaces round it",
            "flag, keep: read as written",
        ),
        (
            "date_outside_month",
            "Line dated outside its file's month",
            "flag, keep",
        ),
        (
            "amount_unreadable",
            "Amount that cannot be read",
            "exclude: no amount",
        ),
        (
            "below_threshold",
            "Line under £25,000, zero or negative (a credit)",
            "flag, keep",
        ),
        (
            "at_threshold",
            "Line of exactly £25,000, the publishing threshold",
            "keep: at the threshold, not under it",
        ),
        (
            "very_large",
            "Very large line: the top 0.1% by amount",
            "flag, keep: the model takes the amount on a log scale",
        ),
        (
            "family_variant",
            "Department Family not in its commonest spelling",
            "keep: one department, so not a feature",
        ),
        (
            "entity_spaces",
            "Entity written with spaces round it",
            "keep: trim the name",
        ),
        (
            "ewr",
            '"EWR" and "East West Rail": one body under two names',
            "keep: merge into one body for results per body",
        ),
        (
            "rare_body",
            f"Body with fewer than an assumed {rare_body_lines} lines in "
            f"{months_held} months",
            "keep: too few lines to judge on its own",
        ),
        (
            "redacted",
            "Supplier redacted by DfT",
            "flag, keep: the supplier is unknown",
        ),
        (
            "placeholder",
            'Placeholder payee, such as "one time vendor"',
            "flag, keep",
        ),
        (
            "supplier_variant",
            "Supplier spelled differently from a commoner name for it "
            "(case, punctuation, Ltd or Limited)",
            "keep: the supplier feature reads parts of words, so near "
            "spellings share signal",
        ),
        (
            "exact_duplicate",
            "Exact duplicate: every published cell repeats an earlier line "
            "(the extra copies)",
            "exclude the extra copies from modelling; the raw data keeps "
            "them",
        ),
        (
            "near_duplicate",
            "Near-duplicate: same supplier, amount, date and transaction "
            "number, differing elsewhere (every line in the group)",
            "flag, keep: each may be a real posting",
        ),
        (
            "split_transaction",
            "Transaction number carrying more than one Expense Type in one "
            "body (every line)",
            "keep: the split is by month, never at random",
        ),
        (
            "no_transaction_number",
            'Transaction No missing ("#" or "N/A")',
            "keep: not a feature",
        ),
        (
            "no_item_text",
            'Item Text missing ("#", "##" or "#N/A")',
            "keep: treat as no text",
        ),
        (
            "label_20",
            "Expense Type exactly 20 characters long, likely cut off",
            "flag, keep",
        ),
        (
            "variant_spaces",
            "Expense Type differing from a commoner spelling in spaces only",
            "keep: merge into the commonest spelling",
        ),
        (
            "variant_case",
            "Expense Type differing from a commoner spelling in case",
            "keep: merge into the commonest spelling",
        ),
        (
            "variant_dash",
            "Expense Type differing from a commoner spelling in a dash, or "
            "a ? in its place",
            "keep: merge into the commonest spelling",
        ),
        (
            "variant_separator",
            "Expense Type differing from a commoner spelling in a separator, "
            "such as / for -",
            "keep: merge into the commonest spelling",
        ),
        (
            "truncation",
            "Expense Type that may be a longer label cut short (the short "
            "side of a pair)",
            "keep: merge the pairs confirmed by eye, and flag the rest",
        ),
        (
            "hs2_auc",
            'HS2 line labelled "AUC" or "AUC / Phase 1", where HS2 otherwise '
            'uses "AUC - Phase 1"',
            'keep: merge into "AUC - Phase 1" if confirmed by eye',
        ),
        (
            "nh_2025",
            f"The 2025 National Highways labels: the {len(new_labels)} "
            '"TA Cost AUC" labels '
            "first used from April 2025",
            "keep: report as found, as concept drift",
        ),
        (
            "unseen_type",
            "Validation or test line whose Expense Type never occurs in "
            "training",
            'keep: it falls into "Other"',
        ),
    ],
    columns=["kind", "anomaly", "proposed treatment"],
).set_index("kind")
print(f"Kinds of anomaly: {len(kinds)}")

Kinds of anomaly: 31

In [20]:
# A payee that is a placeholder for whoever was paid, not a supplier's name.
placeholders = (
    r"ONE TIME|ONE-TIME|ONE OFF|ONE-OFF|SUNDRY|SUNDRIES|MISCELLANEOUS|"
    r"VARIOUS|UNKNOWN|DUMMY"
)
flags = flag_anomalies(
    df,
    variants,
    pairs,
    new_labels,
    published=published,
    cp850_files=cp850_files,
    drift_files=drift_files,
    placeholders=placeholders,
    hs2="High Speed Two (HS2) Limited",
    hs2_labels=["AUC", "AUC / Phase 1"],
    ewr=["EWR", "East West Rail"],
    rare_body_lines=rare_body_lines,
    top_share=0.001,
    threshold=25_000,
)
anomalies = anomaly_table(df, flags, kinds)

copies = df[flags["exact_duplicate"]]
in_file = df.duplicated(published + ["source_file"]) & flags["exact_duplicate"]
print(f"Published total: £{df['amount'].sum():,.2f}")
print(
    f"Exact duplicates: {len(copies):,} extra copies, {in_file.sum():,} of "
    f"them in the same file as the line they repeat, in "
    f"{copies['source_file'].nunique()} files"
)
very_large = df.loc[flags["very_large"], "amount"]
print(f"Top 0.1% by amount: from £{very_large.min():,.2f}")
for name, group in df[flags["hs2_auc"]].groupby("Expense Type"):
    print(
        f'HS2 "{name}": {len(group):,} lines, {group["month"].min()} to '
        f'{group["month"].max()}'
    )
anomalies

Published total: £177,111,208,418.51
Exact duplicates: 329 extra copies, 329 of them in the same file as the line they repeat, in 47 files
Top 0.1% by amount: from £230,643,970.18
HS2 "AUC": 140 lines, 2023-07 to 2023-12
HS2 "AUC ": 334 lines, 2023-07 to 2023-12
HS2 "AUC / Phase 1": 61 lines, 2024-05 to 2024-05

,anomaly,lines,£ in these lines,total £ with them,total £ without them,proposed treatment,ruling
#,,,,,,,
1,Blank row: every published cell empty,657,0.00,"177,111,208,418.51","177,111,208,418.51",exclude: no content,for Paddy to rule
2,Line from one of the 3 files that store £ as byte 0x9C (cp850),8317,"12,296,156,491.49","177,111,208,418.51","164,815,051,927.02","keep: the build reads them as cp850, so every amount is right",for Paddy to rule
3,Line from one of the 5 files that name a column differently,13826,"18,263,369,361.27","177,111,208,418.51","158,847,839,057.24",keep: the build maps the names,for Paddy to rule
4,"Cell holding the spreadsheet error ""#N/A"" or ""N/A""",63,"15,424,730.99","177,111,208,418.51","177,095,783,687.52",keep: treat the cell as missing,for Paddy to rule
5,"Date not written dd/mm/yyyy: dots, or spaces round it",29,"1,909,226.26","177,111,208,418.51","177,109,299,192.25","flag, keep: read as written",for Paddy to rule
6,Line dated outside its file's month,24,"2,561,411.88","177,111,208,418.51","177,108,647,006.63","flag, keep",for Paddy to rule
7,Amount that cannot be read,0,0.00,"177,111,208,418.51","177,111,208,418.51",exclude: no amount,for Paddy to rule
8,"Line under £25,000, zero or negative (a credit)",0,0.00,"177,111,208,418.51","177,111,208,418.51","flag, keep",for Paddy to rule
9,"Line of exactly £25,000, the publishing threshold",171,"4,275,000.00","177,111,208,418.51","177,106,933,418.51","keep: at the threshold, not under it",for Paddy to rule
10,Very large line: the top 0.1% by amount,126,"51,557,542,687.81","177,111,208,418.51","125,553,665,730.70","flag, keep: the model takes the amount on a log scale",for Paddy to rule
11,Department Family not in its commonest spelling,8447,"2,787,958,868.22","177,111,208,418.51","174,323,249,550.29","keep: one department, so not a feature",for Paddy to rule
12,Entity written with spaces round it,1260,"326,044,910.93","177,111,208,418.51","176,785,163,507.58",keep: trim the name,for Paddy to rule
13,"""EWR"" and ""East West Rail"": one body under two names",2338,"334,538,978.09","177,111,208,418.51","176,776,669,440.42",keep: merge into one body for results per body,for Paddy to rule
14,Body with fewer than an assumed 10 lines in 48 months,3,"255,965.72","177,111,208,418.51","177,110,952,452.79",keep: too few lines to judge on its own,for Paddy to rule
15,Supplier redacted by DfT,3563,"1,163,745,373.07","177,111,208,418.51","175,947,463,045.44","flag, keep: the supplier is unknown",for Paddy to rule
16,"Placeholder payee, such as ""one time vendor""",56,"8,307,591.37","177,111,208,418.51","177,102,900,827.14","flag, keep",for Paddy to rule
17,"Supplier spelled differently from a commoner name for it (case, punctuation, Ltd or Limited)",15693,"8,750,797,397.42","177,111,208,418.51","168,360,411,021.09","keep: the supplier feature reads parts of words, so near spellings share signal",for Paddy to rule
18,Exact duplicate: every published cell repeats an earlier line (the extra copies),329,"52,280,103.56","177,111,208,418.51","177,058,928,314.95",exclude the extra copies from modelling; the raw data keeps them,for Paddy to rule
19,"Near-duplicate: same supplier, amount, date and transaction number, differing elsewhere (every line in the group)",300,"497,459,805.53","177,111,208,418.51","176,613,748,612.98","flag, keep: each may be a real posting",for Paddy to rule
20,Transaction number carrying more than one Expense Type in one body (every line),17290,"86,169,567,247.29","177,111,208,418.51","90,941,641,171.22","keep: the split is by month, never at random",for Paddy to rule
21,"Transaction No missing (""#"" or ""N/A"")",10194,"32,115,520,755.96","177,111,208,418.51","144,995,687,662.55",keep: not a feature,for Paddy to rule
22,"Item Text missing (""#"", ""##"" or ""#N/A"")",16197,"26,405,291,557.98","177,111,208,418.51","150,705,916,860.53",keep: treat as no text,for Paddy to rule
23,"Expense Type exactly 20 characters long, likely cut off",22261,"16,888,152,235.73","177,111,208,418.51","160,223,056,182.78","flag, keep",for Paddy to rule
24,Expense Type differing from a commoner spelling in spaces only,438,"1,410,999,389.62","177,111,208,418.51","175,700,209,028.89",keep: merge into the commonest spelling,for Paddy to rule
25,Expense Type differing from a commoner spelling in case,1432,"190,346,051.73","177,111,208,418.51","176,920,862,366.78",keep: merge into the commonest spelling,for Paddy to rule
26,"Expense Type differing from a commoner spelling in a dash, or a ? in its place",353,"57,682,247.84","177,111,208,418.51","177,053,526,170.67",keep: merge into the commonest spelling,for Paddy to rule
27,"Expense Type differing from a commoner spelling in a separator, such as / for -",1506,"1,713,530,667.18","177,111,208,418.51","175,397,677,751.33",keep: merge into the commonest spelling,for Paddy to rule
28,Expense Type that may be a longer label cut short (the short side of a pair),6927,"1,532,885,740.39","177,111,208,418.51","175,578,322,678.12","keep: merge the pairs confirmed by eye, and flag the rest",for Paddy to rule
29,"HS2 line labelled ""AUC"" or ""AUC / Phase 1"", where HS2 otherwise uses ""AUC - Phase 1""",535,"4,857,283,253.17","177,111,208,418.51","172,253,925,165.34","keep: merge into ""AUC - Phase 1"" if confirmed by eye",for Paddy to rule
30,"The 2025 National Highways labels: the 15 ""TA Cost AUC"" labels first used from April 2025",2310,"358,428,220.94","177,111,208,418.51","176,752,780,197.57","keep: report as found, as concept drift",for Paddy to rule
31,Validation or test line whose Expense Type never occurs in training,295,"54,836,523.54","177,111,208,418.51","177,056,371,894.97","keep: it falls into ""Other""",for Paddy to rule

**What the anomaly list shows.** The 31 kinds are measured against a published total of £177,111,208,418.51. Two checks find nothing: every amount reads, and no line is under £25,000, so the file holds no credits.

- **Duplicates.** 329 lines repeat an earlier line in every published cell, each in the same file as the line it repeats, and are worth £52,280,103.56. I propose leaving these extra copies out of modelling, while the raw data keeps them. Another 300 lines share a supplier, amount, date and transaction number with a line that differs elsewhere, worth £497,459,805.53, and I propose to flag and keep them.
- **Payees.** DfT redacted the supplier on 3,563 lines worth £1,163,745,373.07, and 56 lines worth £8,307,591.37 go to placeholder payees.
- **Amounts.** The 126 lines in the top 0.1% by amount start at £230,643,970.18 and hold £51,557,542,687.81 between them.
- **Labels.** Spelling variants cover 3,729 lines, possible truncations 6,927 and labels of exactly 20 characters 22,261. HS2's relabelled AUC lines number 535. The 2025 National Highways labels hold 2,310 lines, and 295 validation or test lines carry a type never seen in training.

Every treatment in the list is a proposal until it is ruled on, and Task 3 applies the rulings.

## Modeling

## Evaluation

## Outputs

## Summary